### ISSUE TITLE
ERROR:  Index 7 out of bounds for length 7

### ISSUE THREAD

**Issue by demis001** [aboyle/F-seq#17]
Got this error:

```
fseq -v -of npf GM12376-DEB-1000.prichr.sorted.rmDup.namesorted.bed -o ../fseqpeaks_21068Rsy/ 
F-Seq Version 1.84
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
	at edu.duke.igsp.gkde.Main.wgShiftCalc(Main.java:353)
	at edu.duke.igsp.gkde.Main.main(Main.java:182)
```

Bed file is a paired end converted the bam to bed format using `samtools bamtobed -bedpe`

```
8	33824398	33824434	8	33824405	33824441	A00755:127:H5FKMDRXY:1:1101:1027:11537	42	-	+
.	-1	-1	.	-1	-1	A00755:127:H5FKMDRXY:1:1101:1027:18865	0	.	.
12	45746880	45746916	12	45747534	45747570	A00755:127:H5FKMDRXY:1:1101:1027:22091	42	+	-
.	-1	-1	.	-1	-1	A00755:127:H5FKMDRXY:1:1101:1027:26349	0	.	.
14	78088611	78088647	14	78088617	78088653	A00755:127:H5FKMDRXY:1:1101:1027:36370	42	-	+
3	128550261	128550297	3	128550392	128550428	A00755:127:H5FKMDRXY:1:1101:1036:3505	42	+	-
21	8252336	8252372	21	8253111	8253147	A00755:127:H5FKMDRXY:1:1101:1036:18787	1	+	-
3	130517241	130517277	3	130517252	130517288	A00755:127:H5FKMDRXY:1:1101:1036:33630	40	-	+
13	98123808	98123844	13	98123868	98123904	A00755:127:H5FKMDRXY:1:1101:1036:34788	42	+	-
20	46791022	46791058	20	46791035	46791071	A00755:127:H5FKMDRXY:1:1101:1045:1892	34	-	+
```

Any idea?

**Comment by aboyle** [comment]
F-seq doesn't take bedpe as input. However, I recommend moving to F-seq 2 that can properly handle paired end read data: https://github.com/Boyle-Lab/F-Seq2
